<?php

namespace AppBundle\Repository;

/**
 * StoreOrderDeliveryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StoreOrderDeliveryRepository extends \Doctrine\ORM\EntityRepository
{
}
