<?php

namespace AppBundle\Repository;

/**
 * StoreOrderProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StoreOrderProductRepository extends \Doctrine\ORM\EntityRepository
{
}
